%% Code that was used for reference in the graphing scripts 

yyaxis left
plot(Cycle,Cap_charge,‘o-’,...
‘LineWidth’,2,...
   ‘MarkerSize’,8);
ylabel (‘Capacity (mAh)’,’FontSize’,20, ‘FontWeight’,‘bold’);
xlabel (‘Cycle’,‘FontSize’,20,‘FontWeight’,‘bold’);
hold on
plot(Cycle,Cap_discharge, ‘o--’,...
‘LineWidth’,2,...
   ‘MarkerSize’,8);
% yticks([0 10 20 30 40 50]);
hold on
yyaxis right
plot (Cycle, Efficiency,‘o-’,...
‘LineWidth’,2,...
   ‘MarkerSize’,8);
ylabel (‘Columbic Efficiency (%)’,’FontSize’,20, ‘FontWeight’,‘bold’);